FROM python:3.12-slim

WORKDIR /app

ENV DEBIAN_CODENAME=bookworm

RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ ${DEBIAN_CODENAME}-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    apt-get update && \
    apt-get install -y postgresql-client-16 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

ENV DEBUG=1 \
    PYTHONUNBUFFERED=1 \
    DEV_POSTGRES_NAME=seemyfamily \
    DEV_POSTGRES_USER=postgres \
    DEV_POSTGRES_PASSWORD=donkey6 \
    DEV_POSTGRES_HOST=db \
    DEV_POSTGRES_PORT=5432

EXPOSE 8000

VOLUME ["/app"]

CMD ["sh", "-c", "python -u manage.py makemigrations && python -u manage.py migrate && python -u manage.py runserver 0.0.0.0:8000"]

