FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

ENV DEBUG=0 \
    PYTHONUNBUFFERED=1


EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && gunicorn --workers 3 --bind 0.0.0.0:8000 backend.wsgi:application"]


