# fly.toml app configuration file generated for backend-small-surf-1752 on 2024-10-15T04:56:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-small-surf-1752'
primary_region = 'atl'

[build]
  dockerfile = './Dockerfile.prod'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
