# Generated by Django 5.1.1 on 2024-09-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
