# Generated by Django 5.1.2 on 2024-10-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_history_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.person'),
        ),
    ]
