# Generated by Django 5.1.2 on 2024-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_photo_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
