# Generated by Django 5.1.4 on 2024-12-06 14:09

from django.db import migrations, models

def copy_birthdate_to_birthyear(apps, schema_editor):
    Person = apps.get_model('api', 'Person')
    for person in Person.objects.all():
        if person.birthdate:
            person.birthyear = person.birthdate.year
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_photo_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthyear',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(copy_birthdate_to_birthyear),
        migrations.RemoveField(
            model_name='person',
            name='birthdate'
        )
    ]
